# Generated by Django 3.2 on 2022-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/DEFAULT-USER-PROFILE-PICTURE.jpg', upload_to='profile_pictures/'),
        ),
    ]
