# Generated by Django 3.2 on 2022-01-12 18:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=3000)),
                ('image', models.ImageField(default='deal_images/DEFAULT-DEAL-IMAGE.jpg', upload_to='deal_images/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(default=None, max_length=500, null=True)),
                ('category', models.CharField(choices=[('GROCERIES', 'GROCERIES'), ('ELECTRONICS', 'ELECTRONICS'), ('SPORT & LEISURE', 'SPORT & LEISURE'), ('FINANCE & INSURANCE', 'FINANCE & INSURANCE'), ('HOME & GARDEN', 'HOME & GARDEN')], max_length=60)),
                ('instore_only', models.BooleanField(default=False)),
                ('postage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sent_from', models.CharField(choices=[('UNITED KINGDOM', 'UNITED KINGDOM'), ('GERMANY', 'GERMANY'), ('FRANCE', 'FRANCE'), ('USA', 'USA'), ('CHINA', 'CHINA')], default=None, max_length=100, null=True)),
                ('deal_start_date', models.DateField(default=None, null=True)),
                ('deal_end_date', models.DateField(default=None, null=True)),
                ('up_votes', models.JSONField(default=list)),
                ('down_votes', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
